### ISSUE TITLE
Landroid - no MQTT Device discovered

### ISSUE THREAD

**Issue by JangoBritt** [stefanlaheij/hassio-addons#10]
Hi,

I've installed this plugin, and connected successfully. The plugin can see my android, but there's no device created under the MQTT auto discovery... Is there something extra I have to do to create the device in HA?

**Comment by stefanlaheij** [comment]
Hi @JangoBritt,

I do'nt think this works with auto discovery. I use the Mosquitto broker add-on to publish the topics to.
Then i use these sensor in the configuration.yaml:

```yaml
sensor:
  - platform: mqtt
    state_topic: "landroid/status/statusDescription"
    name: "Landroid status"
  - platform: mqtt
    state_topic: "landroid/status/errorDescription"
    name: "Landroid error"
  - platform: mqtt
    state_topic: "landroid/status/batteryLevel"
    name: "Landroid battery level"
```
